### ISSUE TITLE
conjure-up openstack fails with "Machine creation errors: 0: Failed to get device attributes: no such file or directory"

### ISSUE THREAD

**Issue by jpmitchell** [ubuntu/conjure-up#227] opened 2016-07-08 17:34 UTC
This failure occurs running the following versions:
Ubuntu 16.04 LTS
conjure-up 2.0.0.4-0~460~ubuntu16.04.1
juju-2.0 2.0-beta11-0ubuntu1~16.04.1~juju1

The following shows up in /var/log/openstack.log
Jul  8 09:02:26 jpmitchell-PowerEdge-R610 conjure-up/openstack: [DEBUG] 00_pre-deploy:20 - Running pre-deploy for OpenStack
Jul  8 09:02:31 jpmitchell-PowerEdge-R610 conjure-up/openstack: [DEBUG] 00_pre-deploy:32 - Processing lxd profile: valentin
Jul  8 09:03:08 jpmitchell-PowerEdge-R610 conjure-up/openstack: [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.
Jul  8 09:03:14 jpmitchell-PowerEdge-R610 conjure-up/openstack: [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.
Jul  8 09:03:15 jpmitchell-PowerEdge-R610 conjure-up/openstack: [ERROR] Failure in deploy done: Machine creation errors:#0120: Failed to get device attributes: no such file or directory
Jul  8 09:03:15 jpmitchell-PowerEdge-R610 conjure-up/openstack: [ERROR] Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjure/controllers/deploystatus/common.py", line 38, in wait_for_applications#012    raise Exception(result['message'])#012Exception: Machine creation errors:#0120: Failed to get device attributes: no such file or directory

The following shows up in lxc list:
jpmitchell@jpmitchell-PowerEdge-R610:~$ lxc list
+---------------+---------+---------------------+------+------------+-----------+
|     NAME      |  STATE  |        IPV4         | IPV6 |    TYPE    | SNAPSHOTS |
+---------------+---------+---------------------+------+------------+-----------+
| juju-7c4332-0 | RUNNING | 10.86.55.168 (eth0) |      | PERSISTENT | 0         |
+---------------+---------+---------------------+------+------------+-----------+

Let me know if you need more or want to try other things. I am even willing to screen share. Thanks.

**Comment by deans75** [comment] 2016-07-11 03:36
I am also seeing the same issue:

This failure also occurs running this following version:
Ubuntu 16.04 LTS
conjure-up 2.0.0
juju-2.0 2.0-beta11
lxd - 2.0.2

**Comment by battlemidget** [comment] 2016-07-11 13:41
Was these on localhost or maas?

**Comment by deans75** [comment] 2016-07-11 14:02
For me - Localhost.

**Comment by battlemidget** [comment] 2016-07-11 14:09
Thanks, doing some testing today to see if i can reproduce

**Comment by deans75** [comment] 2016-07-11 15:29
Awesome - thanks!

**Comment by deans75** [comment] 2016-07-12 13:13
Any luck with the testing?

**Comment by battlemidget** [comment] 2016-07-12 13:13
So far I can't reproduce this, doing a few more runs today on different hardware

**Comment by deans75** [comment] 2016-07-12 13:28
I know OP shows a R610 - I am on esxi 6.0 VM - I can replicate this over and over for the last week. 

Ubuntu Server 16.04, updates and then the following:

http://conjure-up.io/

Error I recieve are not always machine Creation error 0. has been up to and including all 16 machines, varies for what ever reason.

**Comment by fbsobreira** [comment] 2016-07-12 14:04
I was getting the same error on a VM (tested with juju beta7 and beta11). But it seems that the problem is with juju. I was able to bootstrap but could not add any machine with juju, (lxc launch works perfect). Try "juju add-machine" and see if you get the same error:  "juju show-machine" -> "Failed to get device attributes: no such file or directory". 
So I tried conjure-up on my physical server without VM, and it works!

**Comment by battlemidget** [comment] 2016-07-12 14:36
Interesting, I've been testing on bare metal. @deans75 do you have a way to test on bare metal as well? Maybe we can narrow this down some more.

**Comment by jpmitchell** [comment] 2016-07-12 14:55
It is localhost on bare hardware for me. I am willing to screen share on the machine if someone wants to look at it.

**Comment by battlemidget** [comment] 2016-07-12 15:17
Can you provide the output of:

```
lxc profile show juju-default
```

**Comment by jpmitchell** [comment] 2016-07-12 15:26
jpmitchell@jpmitchell-PowerEdge-R610:~$ lxc profile show juju-default
name: juju-default
config:
  boot.autostart: "true"
  linux.kernel_modules: openvswitch,nbd,ip_tables,ip6_tables
  security.nesting: "true"
  security.privileged: "true"
description: ""
devices:
  eth0:
    mtu: "9000"
    name: eth0
    nictype: bridged
    parent: lxdbr0
    type: nic
  eth1:
    mtu: "9000"
    name: eth1
    nictype: bridged
    parent: openstack0
    type: nic
  kvm:
    path: /dev/kvm
    type: unix-char
  mem:
    path: /dev/mem
    type: unix-char
  root:
    path: /
    type: disk
  tun:
    path: /dev/net/tun
    type: unix-char

**Comment by battlemidget** [comment] 2016-07-12 15:37
@jpmitchell i think ive fixed it, can you do a new install?

**Comment by jpmitchell** [comment] 2016-07-12 15:41
Yes. I can. What would you like me to do?

**Comment by battlemidget** [comment] 2016-07-12 15:46
@jpmitchell 

```
juju controllers
juju kill-controller <controller-name>
```

Run this script to cleanup your juju lxc profiles: https://gist.github.com/battlemidget/9c6fc9f0d177624045d2de2612ac85ca

Finally, re-run conjure-up:

```
conjure-up -d openstack
```

the `-d` is for debugging output to /var/log/conjure-up/openstack.log

**Comment by battlemidget** [comment] 2016-07-12 17:06
This should be fixed now as we don't check for KVM support using the openstack with novalxd bundle.

**Closed by battlemidget** 2016-07-12 17:06 UTC
Labels: bug

**Comment by jpmitchell** [comment] 2016-07-12 17:47
This appears to have fixed the issue. Thanks. Ran into another issue with not having keys in .ssh. I will open another bug. Thanks again!

**Comment by battlemidget** [comment] 2016-07-12 17:52
@jpmitchell thanks for testing, that ssh key error has come up before. you can follow that bug here: https://github.com/battlemidget/openstack-novalxd/issues/3

**Comment by deans75** [comment] 2016-07-13 02:20
Can confirm this works. I have yet to hit any keys in .ssh issue.

**Comment by battlemidget** [comment] 2016-07-13 02:24
@deans75 on the system where you are running conjure-up from make sure you've run `ssh-keygen`

**Comment by deans75** [comment] 2016-07-13 02:31
@battlemidget - will do - thanks

**Comment by deans75** [comment] 2016-07-14 14:21
@battlemidget - working as it should at this time - no ssh keygen issues with conjure-up.

**Comment by battlemidget** [comment] 2016-07-14 14:25
@deans75 very cool! Ive also updated the spell to generate an ssh key if none exists. Thanks for testing!
